# Location of this file is /mnt/c/users/<username>/AppData/Roaming/wsltty/config
# To use common configuration in %APPDATA%\mintty, simply remove this file
CursorBlinks=no
Font=Victor Mono
#Leading=0
#Font=Source Han Mono
#FontMenu=1
#FontChoice=Private:2
#Font2=MesloLGS NF
ShowHiddenFonts=yes
Locale=en_US
Language=en_US
BoldAsFont=yes
MiddleClickAction=void
RightClickAction=menu
Rows=42
Columns=120
X=10
Y=10
BoldAsColour=yes
ClipShortcuts=no
WindowShortcuts=no
AltFnShortcuts=no
CtrlShiftShortcuts=yes
BellType=0
#Charwidth=unicode
Charwidth=wcwidth
Padding=3
ThemeFile=gruvbox_dark.minttyrc
FontHeight=14
FontWeight=400
RowSpacing=-1
Emojis=noto
EmojiPlacement=middle
CursorType=block
ClicksTargetApp=no
