-- AI plugin
return {
	-- 	"yetone/avante.nvim",
	-- 	build = "make",
	-- 	dependencies = {
	-- 		"nvim-lua/plenary.nvim",
	-- 		"MunifTanjim/nui.nvim",
	-- 	},
	-- 	event = "VeryLazy",
	-- 	version = false,
	-- 	opts = {
	-- 		debug = true,
	-- 		mode = "legacy",
	-- 		provider = "ollama",
	-- 		providers = {
	-- 			ollama = {
	-- 				endpoint = "http://192.168.13.195:11434",
	-- 				model = "ministral-3:14b",
	-- 				-- model = "devstral-small-2:24b",
	-- 				-- model = "qwen3:14b",
	-- 				keep_alive = "120m",
	-- 				extra_request_body = {
	-- 					options = {
	-- 						temperature = 0.75,
	-- 						num_ctx = 16384,
	-- 					},
	-- 				},
	-- 			},
	-- 		},
	-- 		selector = {
	-- 			provider = "fzf",
	-- 			provider_opts = {},
	-- 		},
	-- 		-- behaviour = {
	-- 		-- 	auto_approve_tool_permissions = true,
	-- 		-- },
	-- 		-- system_prompt as function ensures LLM always has latest MCP server state
	-- 		-- This is evaluated for every message, even in existing chats
	-- 		system_prompt = function()
	-- 			local hub = require("mcphub").get_hub_instance()
	-- 			return hub and hub:get_active_servers_prompt() or ""
	-- 		end,
	-- 		-- Using function prevents requiring mcphub before it's loaded
	-- 		custom_tools = function()
	-- 			return {
	-- 				require("mcphub.extensions.avante").mcp_tool(),
	-- 			}
	-- 		end,
	-- 		mappings = {
	-- 			diff = {
	-- 				ours = "co",
	-- 				theirs = "ct",
	-- 				all_theirs = "ca",
	-- 				both = "cb",
	-- 				cursor = "cc",
	-- 				next = "]x",
	-- 				prev = "[x",
	-- 			},
	-- 			suggestion = {
	-- 				accept = "<M-l>",
	-- 				next = "<M-]>",
	-- 				prev = "<M-[>",
	-- 				dismiss = "<C-]>",
	-- 			},
	-- 			jump = {
	-- 				next = "]]",
	-- 				prev = "[[",
	-- 			},
	-- 			submit = {
	-- 				normal = "<CR>",
	-- 				insert = "<C-s>",
	-- 			},
	-- 			cancel = {
	-- 				normal = { "<C-c>", "<Esc>", "q" },
	-- 				insert = { "<C-c>" },
	-- 			},
	-- 			sidebar = {
	-- 				apply_all = "A",
	-- 				apply_cursor = "a",
	-- 				retry_user_request = "r",
	-- 				edit_user_request = "e",
	-- 				switch_windows = "<Tab>",
	-- 				reverse_switch_windows = "<S-Tab>",
	-- 				remove_file = "d",
	-- 				add_file = "@",
	-- 				close = { "<Esc>", "q" },
	-- 				close_from_input = nil, -- e.g., { normal = "<Esc>", insert = "<C-d>" }
	-- 			},
	-- 		},
	-- 	},
}
